/**
 * page
*/
export const UPDATE_COMPONENTS = 'UPDATE_COMPONENTS'
export const UPDATE_CURRENT_COMPONENTS = 'UPDATE_CURRENT_COMPONENTS'
export const UPDATE_PREV_COMPONENTS = 'UPDATE_PREV_COMPONENTS'
